# conda-recipe/meta.yaml
package:
  name: unicorn
  version: "1.0.0"  # Replace with your project's actual version

source:
  url: https://github.com/GeoGenetics/unicorn/releases/download/v1.0.0/v1.0.0.tar.gz
  sha256: 3613ebfc220afc5cca36d5f74e9ccd2c43f4a9cbb317e79f86d4514ca0bcf7fa

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # Specifies the C compiler for the target platform
    - make                # The 'make' build tool

  host:
    - htslib >=1.10              # The library to link against during compilation

  run:
    - htslib >=1.10              # The library needed at runtime by the executable


about:
  home: "https://github.com/GeoGenetics/unicorn"
  license: MIT
  summary: "A tool for computing statistics on short read alignments."